# Generated by Django 3.1 on 2020-09-06 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artno', models.CharField(max_length=6, unique=True)),
                ('brand', models.CharField(max_length=25)),
                ('style', models.CharField(blank=True, choices=[('v-strap', 'V-STRAP'), ('sandal', 'SANDAL'), ('t-strap', 'T-STRAP'), ('shoes', 'SHOES'), ('', 'None')], max_length=25)),
                ('category', models.CharField(blank=True, choices=[('g', 'Gents'), ('l', 'Ladies'), ('k', 'Kids'), ('c', 'Children'), ('b', 'Boys'), ('r', 'Girls'), ('x', 'Giants'), ('', 'None')], max_length=10)),
                ('article_detail', models.CharField(blank=True, max_length=50)),
                ('color', models.ManyToManyField(to='core.Color')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
