# Generated by Django 3.1 on 2020-09-06 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artno', models.CharField(max_length=6, unique=True)),
                ('brand', models.CharField(choices=[('pride', 'Pride'), ('debongo', 'Debongo'), ('smartak', 'Smartak'), ('stile', 'Stile'), ('lpride', 'L. Pride'), ('disney', 'Disney'), ('batman', 'Batman'), ('kapers', 'Kapers'), ('', 'None')], max_length=25)),
                ('style', models.CharField(choices=[('v-strap', 'V-STRAP'), ('sandal', 'SANDAL'), ('t-strap', 'T-STRAP'), ('covering', 'COVERING'), ('shoes', 'SHOES')], max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
