# Generated by Django 3.1 on 2020-09-06 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='brand',
            field=models.CharField(blank=True, choices=[('pride', 'Pride'), ('debongo', 'Debongo'), ('smartak', 'Smartak'), ('stile', 'Stile'), ('lpride', 'L. Pride'), ('disney', 'Disney'), ('batman', 'Batman'), ('kapers', 'Kapers'), ('', 'None')], max_length=25),
        ),
        migrations.AlterField(
            model_name='article',
            name='style',
            field=models.CharField(blank=True, choices=[('v-strap', 'V-STRAP'), ('sandal', 'SANDAL'), ('t-strap', 'T-STRAP'), ('covering', 'COVERING'), ('shoes', 'SHOES'), ('', 'None')], max_length=25),
        ),
        migrations.CreateModel(
            name='ArticleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('art_id', models.CharField(max_length=12)),
                ('basic', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('export', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.article')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.color')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
