# Generated by Django 3.1 on 2020-09-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='style',
            field=models.CharField(choices=[('v-strap', 'V-STRAP'), ('sandal', 'SANDAL'), ('t-strap', 'T-STRAP'), ('covering', 'COVERING'), ('shoes', 'SHOES')], max_length=25),
        ),
    ]
