# Generated by Django 3.1 on 2020-09-06 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200906_0755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='color',
            new_name='colors',
        ),
    ]
