# Generated by Django 3.1.1 on 2020-09-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_articleinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='brand',
            field=models.CharField(blank=True, choices=[('pride', 'Pride'), ('debongo', 'Debongo'), ('smartak', 'Smartak'), ('stile', 'Stile'), ('lpride', 'L. Pride'), ('disney', 'Disney'), ('batman', 'Batman'), ('kapers', 'Kapers')], max_length=25),
        ),
        migrations.AlterField(
            model_name='article',
            name='style',
            field=models.CharField(blank=True, choices=[('v-strap', 'V-STRAP'), ('sandal', 'SANDAL'), ('t-strap', 'T-STRAP'), ('covering', 'COVERING'), ('shoes', 'SHOES')], max_length=25),
        ),
        migrations.AlterField(
            model_name='articleinfo',
            name='category',
            field=models.CharField(choices=[('g', 'Gents'), ('l', 'Ladies'), ('x', 'Giants'), ('k', 'Kids'), ('b', 'Boys'), ('r', 'Girls'), ('c', 'Children')], max_length=1),
        ),
    ]
