# Generated by Django 3.1 on 2020-09-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200908_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledetail',
            name='category',
            field=models.CharField(max_length=1),
        ),
    ]
