# Generated by Django 3.1.1 on 2020-10-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200920_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleinfo',
            name='mcategory',
            field=models.CharField(default='unknown', max_length=10),
        ),
    ]
