# Generated by Django 3.1 on 2020-09-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200908_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledetail',
            name='category',
            field=models.CharField(choices=[('g', 'Gents'), ('l', 'Ladies'), ('b', 'Boys'), ('k', 'Kids'), ('c', 'Children'), ('x', 'Giants'), ('i', 'Infant')], max_length=1),
        ),
    ]
