# Generated by Django 3.1.1 on 2020-10-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_articleinfo_mcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemcode', models.CharField(max_length=18, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('store', models.CharField(blank=True, choices=[('rexin', 'Rexin'), ('component', 'Component'), ('chemical', 'Chemical'), ('packing', 'Packing')], max_length=25)),
                ('uom', models.CharField(blank=True, max_length=15)),
                ('purchaseuom', models.CharField(blank=True, max_length=15)),
                ('conversionuom', models.DecimalField(decimal_places=2, max_digits=12)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
