# Generated by Django 3.1.1 on 2020-10-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='store',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='itemcode',
            new_name='code',
        ),
        migrations.AddField(
            model_name='material',
            name='subcategory',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
