# Generated by Django 3.1.1 on 2020-10-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201012_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='material',
            name='conversionuom',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
        ),
    ]
