# Generated by Django 3.1.1 on 2020-10-12 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201012_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='conversionuom',
            new_name='cf',
        ),
    ]
