# Generated by Django 3.1.1 on 2020-10-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201012_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='purchaseuom',
            field=models.CharField(blank=True, choices=[('pairs', 'Pair'), ('kilogram', 'Kilogram'), ('meter', 'Meter'), ('cone', 'Cone'), ('roll', 'Roll'), ('nos', 'Nos'), ('gram', 'Gram')], max_length=15),
        ),
        migrations.AlterField(
            model_name='material',
            name='uom',
            field=models.CharField(blank=True, choices=[('pairs', 'Pair'), ('kilogram', 'Kilogram'), ('meter', 'Meter'), ('nos', 'Nos')], max_length=15),
        ),
    ]
